spring.application.name=Mini-ERP

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/minierp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:minierp}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:minierp123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.h2.console.enabled=false

app.jwt.secret=${APP_JWT_SECRET:ReplaceThisWithALongRandomSecretKeyOfAtLeast32Chars}
app.jwt.expiration-ms=86400000

app.system-admin.login-id=sysadmin
app.system-admin.email=sysadmin@shivfurniture.com
app.system-admin.password=Admin@123
app.system-admin.full-name=System Administrator

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

app.upload.dir=/app/uploads/products